# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  checks: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.15
      uses: actions/setup-node@v3
      with:
        node-version: 16.15
        cache: 'npm'
    - run: npm ci
    - run: npm run build:examples
    - run: npm run test:examples
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: ${{ github.workspace }}/examples/angular/pokemon-catalog/target/component/coverage-final.json
        verbose: true
    - name: Test Report
      uses: phoenix-actions/test-reporting@v8
      id: test-report               # Set ID reference for step
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: JEST Tests            # Name of the check run which will be created
        path: examples/angular/pokemon-catalog/target/surefire-reports/*.xml   # Path to test results
        reporter: mocha-junit-reporter        # Format of test results
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          examples/angular/pokemon-catalog/target/surefire-reports/*.xml
    - run: npm run validate:examples
    - run: npm run e2e:examples

  
